services:
  - hostname: graylog
    type: go@1

    verticalAutoscaling:
      minVCpu: 1
      maxVCpu: 5
      cpuMode: DEDICATED
      minRam: 4
      maxRam: 32
      minDisk: 1
      maxDisk: 100


    enableSubdomainAccess: true

    buildFromGit: "https://github.com/culiiik/recipe-graylog"

    zeropsSetup: graylog